//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 04:04:40 AM EST 
//


package edu.buffalo.csse.its.xmlbinding.assay;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.temp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.temp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ROW }
     * 
     */
    public ROW createROW() {
        return new ROW();
    }

    /**
     * Create an instance of {@link RESULTS }
     * 
     */
    public RESULTS createRESULTS() {
        return new RESULTS();
    }

    /**
     * Create an instance of {@link COLUMN }
     * 
     */
    public COLUMN createCOLUMN() {
        return new COLUMN();
    }

}
