//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 03:19:35 AM EST 
//


package edu.buffalo.csse.its.xmlbinding.cmshistory;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DEVICEID" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="DEVICETYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="LOCALUPDATETIME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="NUMBEROFPHASES" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="PHASE1LINE1TEXT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PHASE1LINE2TEXT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PHASE1LINE3TEXT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PHASE2LINE1TEXT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PHASE2LINE2TEXT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PHASE2LINE3TEXT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STATICTEXT1" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="STATICTEXT2" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STATICTEXT3" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="UNIVERSALUPDATETIME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ROW")
public class ROW {

    @XmlAttribute(name = "DEVICEID", required = true)
    protected BigDecimal deviceid;
    @XmlAttribute(name = "DEVICETYPE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String devicetype;
    @XmlAttribute(name = "LOCALUPDATETIME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String localupdatetime;
    @XmlAttribute(name = "NUMBEROFPHASES", required = true)
    protected BigDecimal numberofphases;
    @XmlAttribute(name = "PHASE1LINE1TEXT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String phase1LINE1TEXT;
    @XmlAttribute(name = "PHASE1LINE2TEXT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String phase1LINE2TEXT;
    @XmlAttribute(name = "PHASE1LINE3TEXT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String phase1LINE3TEXT;
    @XmlAttribute(name = "PHASE2LINE1TEXT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String phase2LINE1TEXT;
    @XmlAttribute(name = "PHASE2LINE2TEXT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String phase2LINE2TEXT;
    @XmlAttribute(name = "PHASE2LINE3TEXT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String phase2LINE3TEXT;
    @XmlAttribute(name = "STATICTEXT1", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String statictext1;
    @XmlAttribute(name = "STATICTEXT2", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String statictext2;
    @XmlAttribute(name = "STATICTEXT3", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String statictext3;
    @XmlAttribute(name = "UNIVERSALUPDATETIME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String universalupdatetime;

    /**
     * Gets the value of the deviceid property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDEVICEID() {
        return deviceid;
    }

    /**
     * Sets the value of the deviceid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDEVICEID(BigDecimal value) {
        this.deviceid = value;
    }

    /**
     * Gets the value of the devicetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEVICETYPE() {
        return devicetype;
    }

    /**
     * Sets the value of the devicetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEVICETYPE(String value) {
        this.devicetype = value;
    }

    /**
     * Gets the value of the localupdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCALUPDATETIME() {
        return localupdatetime;
    }

    /**
     * Sets the value of the localupdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCALUPDATETIME(String value) {
        this.localupdatetime = value;
    }

    /**
     * Gets the value of the numberofphases property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNUMBEROFPHASES() {
        return numberofphases;
    }

    /**
     * Sets the value of the numberofphases property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNUMBEROFPHASES(BigDecimal value) {
        this.numberofphases = value;
    }

    /**
     * Gets the value of the phase1LINE1TEXT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHASE1LINE1TEXT() {
        return phase1LINE1TEXT;
    }

    /**
     * Sets the value of the phase1LINE1TEXT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHASE1LINE1TEXT(String value) {
        this.phase1LINE1TEXT = value;
    }

    /**
     * Gets the value of the phase1LINE2TEXT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHASE1LINE2TEXT() {
        return phase1LINE2TEXT;
    }

    /**
     * Sets the value of the phase1LINE2TEXT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHASE1LINE2TEXT(String value) {
        this.phase1LINE2TEXT = value;
    }

    /**
     * Gets the value of the phase1LINE3TEXT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHASE1LINE3TEXT() {
        return phase1LINE3TEXT;
    }

    /**
     * Sets the value of the phase1LINE3TEXT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHASE1LINE3TEXT(String value) {
        this.phase1LINE3TEXT = value;
    }

    /**
     * Gets the value of the phase2LINE1TEXT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHASE2LINE1TEXT() {
        return phase2LINE1TEXT;
    }

    /**
     * Sets the value of the phase2LINE1TEXT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHASE2LINE1TEXT(String value) {
        this.phase2LINE1TEXT = value;
    }

    /**
     * Gets the value of the phase2LINE2TEXT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHASE2LINE2TEXT() {
        return phase2LINE2TEXT;
    }

    /**
     * Sets the value of the phase2LINE2TEXT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHASE2LINE2TEXT(String value) {
        this.phase2LINE2TEXT = value;
    }

    /**
     * Gets the value of the phase2LINE3TEXT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHASE2LINE3TEXT() {
        return phase2LINE3TEXT;
    }

    /**
     * Sets the value of the phase2LINE3TEXT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHASE2LINE3TEXT(String value) {
        this.phase2LINE3TEXT = value;
    }

    /**
     * Gets the value of the statictext1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATICTEXT1() {
        return statictext1;
    }

    /**
     * Sets the value of the statictext1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATICTEXT1(String value) {
        this.statictext1 = value;
    }

    /**
     * Gets the value of the statictext2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATICTEXT2() {
        return statictext2;
    }

    /**
     * Sets the value of the statictext2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATICTEXT2(String value) {
        this.statictext2 = value;
    }

    /**
     * Gets the value of the statictext3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATICTEXT3() {
        return statictext3;
    }

    /**
     * Sets the value of the statictext3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATICTEXT3(String value) {
        this.statictext3 = value;
    }

    /**
     * Gets the value of the universalupdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNIVERSALUPDATETIME() {
        return universalupdatetime;
    }

    /**
     * Sets the value of the universalupdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNIVERSALUPDATETIME(String value) {
        this.universalupdatetime = value;
    }

}
