//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 03:25:20 AM EST 
//


package edu.buffalo.csse.its.xmlbinding.externalagencyhistory;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="AGENCY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ARRIVALTIME" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="ATEID" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="DEPARTURETIME" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="DETECTIONTIME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="LOCALUPDATETIME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="NOTIFICATIONTIME" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="UNIVERSALUPDATETIME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ROW")
public class ROW {

    @XmlAttribute(name = "AGENCY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String agency;
    @XmlAttribute(name = "ARRIVALTIME", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String arrivaltime;
    @XmlAttribute(name = "ATEID", required = true)
    protected BigDecimal ateid;
    @XmlAttribute(name = "DEPARTURETIME", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String departuretime;
    @XmlAttribute(name = "DETECTIONTIME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String detectiontime;
    @XmlAttribute(name = "LOCALUPDATETIME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String localupdatetime;
    @XmlAttribute(name = "NOTIFICATIONTIME", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String notificationtime;
    @XmlAttribute(name = "UNIVERSALUPDATETIME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String universalupdatetime;

    /**
     * Gets the value of the agency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGENCY() {
        return agency;
    }

    /**
     * Sets the value of the agency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGENCY(String value) {
        this.agency = value;
    }

    /**
     * Gets the value of the arrivaltime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getARRIVALTIME() {
        return arrivaltime;
    }

    /**
     * Sets the value of the arrivaltime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setARRIVALTIME(String value) {
        this.arrivaltime = value;
    }

    /**
     * Gets the value of the ateid property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getATEID() {
        return ateid;
    }

    /**
     * Sets the value of the ateid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setATEID(BigDecimal value) {
        this.ateid = value;
    }

    /**
     * Gets the value of the departuretime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEPARTURETIME() {
        return departuretime;
    }

    /**
     * Sets the value of the departuretime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEPARTURETIME(String value) {
        this.departuretime = value;
    }

    /**
     * Gets the value of the detectiontime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDETECTIONTIME() {
        return detectiontime;
    }

    /**
     * Sets the value of the detectiontime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDETECTIONTIME(String value) {
        this.detectiontime = value;
    }

    /**
     * Gets the value of the localupdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCALUPDATETIME() {
        return localupdatetime;
    }

    /**
     * Sets the value of the localupdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCALUPDATETIME(String value) {
        this.localupdatetime = value;
    }

    /**
     * Gets the value of the notificationtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOTIFICATIONTIME() {
        return notificationtime;
    }

    /**
     * Sets the value of the notificationtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOTIFICATIONTIME(String value) {
        this.notificationtime = value;
    }

    /**
     * Gets the value of the universalupdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNIVERSALUPDATETIME() {
        return universalupdatetime;
    }

    /**
     * Sets the value of the universalupdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNIVERSALUPDATETIME(String value) {
        this.universalupdatetime = value;
    }

}
