//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 03:17:24 AM EST 
//


package edu.buffalo.csse.its.xmlbinding.bcdeventhistory;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ACTION" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="CONFIRMATIONTIME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="DESCRIPTION" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="LOCALUPDATETIME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="OWNER" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PEACEBRIDGEDELAYCANADATOUS" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="PEACEBRIDGEDELAYUSTOCANADA" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="QLBRIDGEDELAYCANADATOUS" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="QLBRIDGEDELAYUSTOCANADA" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="RAINBOWBRIDGEDELAYCANADATOUS" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="RAINBOWBRIDGEDELAYUSTOCANADA" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="SOURCE" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="STATE" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="UNIVERSALUPDATETIME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ROW")
public class ROW {

    @XmlAttribute(name = "ACTION", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String action;
    @XmlAttribute(name = "CONFIRMATIONTIME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String confirmationtime;
    @XmlAttribute(name = "DESCRIPTION", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String description;
    @XmlAttribute(name = "ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "LOCALUPDATETIME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String localupdatetime;
    @XmlAttribute(name = "OWNER", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String owner;
    @XmlAttribute(name = "PEACEBRIDGEDELAYCANADATOUS", required = true)
    protected BigDecimal peacebridgedelaycanadatous;
    @XmlAttribute(name = "PEACEBRIDGEDELAYUSTOCANADA", required = true)
    protected BigDecimal peacebridgedelayustocanada;
    @XmlAttribute(name = "QLBRIDGEDELAYCANADATOUS", required = true)
    protected BigDecimal qlbridgedelaycanadatous;
    @XmlAttribute(name = "QLBRIDGEDELAYUSTOCANADA", required = true)
    protected BigDecimal qlbridgedelayustocanada;
    @XmlAttribute(name = "RAINBOWBRIDGEDELAYCANADATOUS", required = true)
    protected BigDecimal rainbowbridgedelaycanadatous;
    @XmlAttribute(name = "RAINBOWBRIDGEDELAYUSTOCANADA", required = true)
    protected BigDecimal rainbowbridgedelayustocanada;
    @XmlAttribute(name = "SOURCE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String source;
    @XmlAttribute(name = "STATE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String state;
    @XmlAttribute(name = "UNIVERSALUPDATETIME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String universalupdatetime;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTION() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTION(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the confirmationtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFIRMATIONTIME() {
        return confirmationtime;
    }

    /**
     * Sets the value of the confirmationtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFIRMATIONTIME(String value) {
        this.confirmationtime = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the localupdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCALUPDATETIME() {
        return localupdatetime;
    }

    /**
     * Sets the value of the localupdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCALUPDATETIME(String value) {
        this.localupdatetime = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOWNER() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOWNER(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the peacebridgedelaycanadatous property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPEACEBRIDGEDELAYCANADATOUS() {
        return peacebridgedelaycanadatous;
    }

    /**
     * Sets the value of the peacebridgedelaycanadatous property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPEACEBRIDGEDELAYCANADATOUS(BigDecimal value) {
        this.peacebridgedelaycanadatous = value;
    }

    /**
     * Gets the value of the peacebridgedelayustocanada property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPEACEBRIDGEDELAYUSTOCANADA() {
        return peacebridgedelayustocanada;
    }

    /**
     * Sets the value of the peacebridgedelayustocanada property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPEACEBRIDGEDELAYUSTOCANADA(BigDecimal value) {
        this.peacebridgedelayustocanada = value;
    }

    /**
     * Gets the value of the qlbridgedelaycanadatous property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQLBRIDGEDELAYCANADATOUS() {
        return qlbridgedelaycanadatous;
    }

    /**
     * Sets the value of the qlbridgedelaycanadatous property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQLBRIDGEDELAYCANADATOUS(BigDecimal value) {
        this.qlbridgedelaycanadatous = value;
    }

    /**
     * Gets the value of the qlbridgedelayustocanada property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQLBRIDGEDELAYUSTOCANADA() {
        return qlbridgedelayustocanada;
    }

    /**
     * Sets the value of the qlbridgedelayustocanada property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQLBRIDGEDELAYUSTOCANADA(BigDecimal value) {
        this.qlbridgedelayustocanada = value;
    }

    /**
     * Gets the value of the rainbowbridgedelaycanadatous property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRAINBOWBRIDGEDELAYCANADATOUS() {
        return rainbowbridgedelaycanadatous;
    }

    /**
     * Sets the value of the rainbowbridgedelaycanadatous property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRAINBOWBRIDGEDELAYCANADATOUS(BigDecimal value) {
        this.rainbowbridgedelaycanadatous = value;
    }

    /**
     * Gets the value of the rainbowbridgedelayustocanada property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRAINBOWBRIDGEDELAYUSTOCANADA() {
        return rainbowbridgedelayustocanada;
    }

    /**
     * Sets the value of the rainbowbridgedelayustocanada property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRAINBOWBRIDGEDELAYUSTOCANADA(BigDecimal value) {
        this.rainbowbridgedelayustocanada = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOURCE() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOURCE(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATE() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATE(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the universalupdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNIVERSALUPDATETIME() {
        return universalupdatetime;
    }

    /**
     * Sets the value of the universalupdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNIVERSALUPDATETIME(String value) {
        this.universalupdatetime = value;
    }

}
