//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.12 at 11:41:10 PM EST 
//


package edu.buffalo.csse.its.xmlbinding.incidentlog;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Closed"/>
 *         &lt;element ref="{}ClosedTime" minOccurs="0"/>
 *         &lt;element ref="{}lockedID"/>
 *         &lt;element ref="{}ID"/>
 *         &lt;element ref="{}ID_x0020_Key"/>
 *         &lt;element ref="{}OperatorsResponse"/>
 *         &lt;element ref="{}Cross_x0020_Street"/>
 *         &lt;element ref="{}Direction"/>
 *         &lt;element ref="{}Route_x002F__x0020_Street"/>
 *         &lt;element ref="{}Municipality"/>
 *         &lt;element ref="{}Event_x0020_Description"/>
 *         &lt;element ref="{}Caller_x0020_Organization"/>
 *         &lt;element ref="{}Caller_x0020_Phone_x0020__x0023_"/>
 *         &lt;element ref="{}Caller_x0020_Name"/>
 *         &lt;element ref="{}Gen_x0020_Event"/>
 *         &lt;element ref="{}Operators"/>
 *         &lt;element ref="{}time"/>
 *         &lt;element ref="{}Date"/>
 *         &lt;element ref="{}Owning_x0020_Agency"/>
 *         &lt;element ref="{}DetectionTime"/>
 *         &lt;element ref="{}VerifyTime"/>
 *         &lt;element ref="{}SceneArrTime" minOccurs="0"/>
 *         &lt;element ref="{}SceneArrTimeSpan"/>
 *         &lt;element ref="{}SceneArrTimeSpanMod"/>
 *         &lt;element ref="{}SceneArrTimeSpanMax"/>
 *         &lt;element ref="{}LanBlockClearTime" minOccurs="0"/>
 *         &lt;element ref="{}LanBlcokClearTimeSpan"/>
 *         &lt;element ref="{}LanBlcokClearTimeSpanMod"/>
 *         &lt;element ref="{}LanBlcokClearTimeSpanMax"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}ClearTime"/>
 *           &lt;element ref="{}SceneDepartTime"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}RetNormTime" minOccurs="0"/>
 *         &lt;element ref="{}RetNormTimeSpan"/>
 *         &lt;element ref="{}RetNormTimeSpanMod"/>
 *         &lt;element ref="{}RetNormTimeSpanMax"/>
 *         &lt;element ref="{}TotalClearTime"/>
 *         &lt;element ref="{}DMS"/>
 *         &lt;element ref="{}DMS_x0020_Act_x0020_Time" minOccurs="0"/>
 *         &lt;element ref="{}DMS_x0020_DeAct_x0020_Time" minOccurs="0"/>
 *         &lt;element ref="{}PVMS"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}PVMS_x0020_Act_x0020_Time"/>
 *           &lt;element ref="{}PVMS_x0020_DeAct_x0020_Time"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}HAR"/>
 *         &lt;element ref="{}CARS_x0020_active"/>
 *         &lt;element ref="{}CARS_x0020_deactive"/>
 *         &lt;element ref="{}CARS_x0020_Man_x0020_Act"/>
 *         &lt;element ref="{}CARS_x0020_Man_x0020_DeAct"/>
 *         &lt;element ref="{}Website_x0020_added_x0020_incident"/>
 *         &lt;element ref="{}Website_x0020_deleted_x0020_incident"/>
 *         &lt;element ref="{}LaneBlocked"/>
 *         &lt;element ref="{}ModTime"/>
 *         &lt;element ref="{}FullRoadClosure"/>
 *         &lt;element ref="{}DMSActiveList" minOccurs="0"/>
 *         &lt;element ref="{}TransAlert_x0020_Act"/>
 *         &lt;element ref="{}TransAlert_x0020_DeAct"/>
 *         &lt;element ref="{}TCWS"/>
 *         &lt;element ref="{}Skyway"/>
 *         &lt;element ref="{}CharmsEventNoAction"/>
 *         &lt;element ref="{}HICFSent"/>
 *         &lt;element ref="{}HARSlot"/>
 *         &lt;element ref="{}CRDMS_x0020_Act"/>
 *         &lt;element ref="{}CRDMS_x0020_DeAct"/>
 *         &lt;element ref="{}CRFaxEmail_x0020_Act"/>
 *         &lt;element ref="{}CRFaxEmail_x0020_DeAct"/>
 *         &lt;element ref="{}CRWeb_x0020_Act"/>
 *         &lt;element ref="{}CRWeb_x0020_DeAct"/>
 *         &lt;element ref="{}Num_x0020_Lanes_x0020_Blocked"/>
 *         &lt;element ref="{}HICFFinalSent"/>
 *         &lt;element ref="{}SceneATS"/>
 *         &lt;element ref="{}LaneBCTS"/>
 *         &lt;element ref="{}RetNTS"/>
 *         &lt;element ref="{}ExcludeFromRep"/>
 *         &lt;element ref="{}SecondaryIncident"/>
 *         &lt;element ref="{}SecondaryIncidentLogNum" minOccurs="0"/>
 *         &lt;element ref="{}IncSeverity"/>
 *         &lt;element ref="{}IncSeverityMod"/>
 *         &lt;element ref="{}IncSeverityMaj"/>
 *         &lt;element ref="{}CREventID" minOccurs="0"/>
 *         &lt;element ref="{}DetectMethod"/>
 *         &lt;element ref="{}LogType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "closed",
    "closedTime",
    "lockedID",
    "id",
    "idx0020Key",
    "operatorsResponse",
    "crossX0020Street",
    "direction",
    "routeX002FX0020Street",
    "municipality",
    "eventX0020Description",
    "callerX0020Organization",
    "callerX0020PhoneX0020X0023",
    "callerX0020Name",
    "genX0020Event",
    "operators",
    "time",
    "date",
    "owningX0020Agency",
    "detectionTime",
    "verifyTime",
    "sceneArrTime",
    "sceneArrTimeSpan",
    "sceneArrTimeSpanMod",
    "sceneArrTimeSpanMax",
    "lanBlockClearTime",
    "lanBlcokClearTimeSpan",
    "lanBlcokClearTimeSpanMod",
    "lanBlcokClearTimeSpanMax",
    "clearTime",
    "sceneDepartTime",
    "retNormTime",
    "retNormTimeSpan",
    "retNormTimeSpanMod",
    "retNormTimeSpanMax",
    "totalClearTime",
    "dms",
    "dmsx0020ActX0020Time",
    "dmsx0020DeActX0020Time",
    "pvms",
    "pvmsx0020ActX0020Time",
    "pvmsx0020DeActX0020Time",
    "har",
    "carsx0020Active",
    "carsx0020Deactive",
    "carsx0020ManX0020Act",
    "carsx0020ManX0020DeAct",
    "websiteX0020AddedX0020Incident",
    "websiteX0020DeletedX0020Incident",
    "laneBlocked",
    "modTime",
    "fullRoadClosure",
    "dmsActiveList",
    "transAlertX0020Act",
    "transAlertX0020DeAct",
    "tcws",
    "skyway",
    "charmsEventNoAction",
    "hicfSent",
    "harSlot",
    "crdmsx0020Act",
    "crdmsx0020DeAct",
    "crFaxEmailX0020Act",
    "crFaxEmailX0020DeAct",
    "crWebX0020Act",
    "crWebX0020DeAct",
    "numX0020LanesX0020Blocked",
    "hicfFinalSent",
    "sceneATS",
    "laneBCTS",
    "retNTS",
    "excludeFromRep",
    "secondaryIncident",
    "secondaryIncidentLogNum",
    "incSeverity",
    "incSeverityMod",
    "incSeverityMaj",
    "crEventID",
    "detectMethod",
    "logType"
})
@XmlRootElement(name = "Incident_x0020_Log")
public class IncidentX0020Log {

    @XmlElement(name = "Closed", required = true)
    protected BigInteger closed;
    @XmlElement(name = "ClosedTime")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String closedTime;
    @XmlElement(required = true)
    protected BigInteger lockedID;
    @XmlElement(name = "ID", required = true)
    protected BigInteger id;
    @XmlElement(name = "ID_x0020_Key", required = true)
    protected BigInteger idx0020Key;
    @XmlElement(name = "OperatorsResponse", required = true)
    protected String operatorsResponse;
    @XmlElement(name = "Cross_x0020_Street", required = true)
    protected String crossX0020Street;
    @XmlElement(name = "Direction", required = true)
    protected String direction;
    @XmlElement(name = "Route_x002F__x0020_Street", required = true)
    protected String routeX002FX0020Street;
    @XmlElement(name = "Municipality", required = true)
    protected String municipality;
    @XmlElement(name = "Event_x0020_Description", required = true)
    protected String eventX0020Description;
    @XmlElement(name = "Caller_x0020_Organization", required = true)
    protected String callerX0020Organization;
    @XmlElement(name = "Caller_x0020_Phone_x0020__x0023_", required = true)
    protected String callerX0020PhoneX0020X0023;
    @XmlElement(name = "Caller_x0020_Name", required = true)
    protected String callerX0020Name;
    @XmlElement(name = "Gen_x0020_Event", required = true)
    protected String genX0020Event;
    @XmlElement(name = "Operators", required = true)
    protected String operators;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String time;
    @XmlElement(name = "Date", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String date;
    @XmlElement(name = "Owning_x0020_Agency", required = true)
    protected String owningX0020Agency;
    @XmlElement(name = "DetectionTime", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String detectionTime;
    @XmlElement(name = "VerifyTime", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String verifyTime;
    @XmlElement(name = "SceneArrTime")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String sceneArrTime;
    @XmlElement(name = "SceneArrTimeSpan", required = true)
    protected BigInteger sceneArrTimeSpan;
    @XmlElement(name = "SceneArrTimeSpanMod", required = true)
    protected BigInteger sceneArrTimeSpanMod;
    @XmlElement(name = "SceneArrTimeSpanMax", required = true)
    protected BigInteger sceneArrTimeSpanMax;
    @XmlElement(name = "LanBlockClearTime")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String lanBlockClearTime;
    @XmlElement(name = "LanBlcokClearTimeSpan", required = true)
    protected BigInteger lanBlcokClearTimeSpan;
    @XmlElement(name = "LanBlcokClearTimeSpanMod", required = true)
    protected BigInteger lanBlcokClearTimeSpanMod;
    @XmlElement(name = "LanBlcokClearTimeSpanMax", required = true)
    protected BigInteger lanBlcokClearTimeSpanMax;
    @XmlElement(name = "ClearTime")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String clearTime;
    @XmlElement(name = "SceneDepartTime")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String sceneDepartTime;
    @XmlElement(name = "RetNormTime")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String retNormTime;
    @XmlElement(name = "RetNormTimeSpan", required = true)
    protected BigInteger retNormTimeSpan;
    @XmlElement(name = "RetNormTimeSpanMod", required = true)
    protected BigInteger retNormTimeSpanMod;
    @XmlElement(name = "RetNormTimeSpanMax", required = true)
    protected BigInteger retNormTimeSpanMax;
    @XmlElement(name = "TotalClearTime", required = true)
    protected BigInteger totalClearTime;
    @XmlElement(name = "DMS", required = true)
    protected BigInteger dms;
    @XmlElement(name = "DMS_x0020_Act_x0020_Time")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String dmsx0020ActX0020Time;
    @XmlElement(name = "DMS_x0020_DeAct_x0020_Time")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String dmsx0020DeActX0020Time;
    @XmlElement(name = "PVMS", required = true)
    protected BigInteger pvms;
    @XmlElement(name = "PVMS_x0020_Act_x0020_Time")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String pvmsx0020ActX0020Time;
    @XmlElement(name = "PVMS_x0020_DeAct_x0020_Time")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String pvmsx0020DeActX0020Time;
    @XmlElement(name = "HAR", required = true)
    protected BigInteger har;
    @XmlElement(name = "CARS_x0020_active", required = true)
    protected BigInteger carsx0020Active;
    @XmlElement(name = "CARS_x0020_deactive", required = true)
    protected BigInteger carsx0020Deactive;
    @XmlElement(name = "CARS_x0020_Man_x0020_Act", required = true)
    protected BigInteger carsx0020ManX0020Act;
    @XmlElement(name = "CARS_x0020_Man_x0020_DeAct", required = true)
    protected BigInteger carsx0020ManX0020DeAct;
    @XmlElement(name = "Website_x0020_added_x0020_incident", required = true)
    protected BigInteger websiteX0020AddedX0020Incident;
    @XmlElement(name = "Website_x0020_deleted_x0020_incident", required = true)
    protected BigInteger websiteX0020DeletedX0020Incident;
    @XmlElement(name = "LaneBlocked", required = true)
    protected BigInteger laneBlocked;
    @XmlElement(name = "ModTime", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String modTime;
    @XmlElement(name = "FullRoadClosure", required = true)
    protected BigInteger fullRoadClosure;
    @XmlElement(name = "DMSActiveList")
    protected String dmsActiveList;
    @XmlElement(name = "TransAlert_x0020_Act", required = true)
    protected BigInteger transAlertX0020Act;
    @XmlElement(name = "TransAlert_x0020_DeAct", required = true)
    protected BigInteger transAlertX0020DeAct;
    @XmlElement(name = "TCWS", required = true)
    protected BigInteger tcws;
    @XmlElement(name = "Skyway", required = true)
    protected BigInteger skyway;
    @XmlElement(name = "CharmsEventNoAction", required = true)
    protected BigInteger charmsEventNoAction;
    @XmlElement(name = "HICFSent", required = true)
    protected BigInteger hicfSent;
    @XmlElement(name = "HARSlot", required = true)
    protected BigInteger harSlot;
    @XmlElement(name = "CRDMS_x0020_Act", required = true)
    protected BigInteger crdmsx0020Act;
    @XmlElement(name = "CRDMS_x0020_DeAct", required = true)
    protected BigInteger crdmsx0020DeAct;
    @XmlElement(name = "CRFaxEmail_x0020_Act", required = true)
    protected BigInteger crFaxEmailX0020Act;
    @XmlElement(name = "CRFaxEmail_x0020_DeAct", required = true)
    protected BigInteger crFaxEmailX0020DeAct;
    @XmlElement(name = "CRWeb_x0020_Act", required = true)
    protected BigInteger crWebX0020Act;
    @XmlElement(name = "CRWeb_x0020_DeAct", required = true)
    protected BigInteger crWebX0020DeAct;
    @XmlElement(name = "Num_x0020_Lanes_x0020_Blocked", required = true)
    protected BigInteger numX0020LanesX0020Blocked;
    @XmlElement(name = "HICFFinalSent", required = true)
    protected BigInteger hicfFinalSent;
    @XmlElement(name = "SceneATS", required = true)
    protected BigInteger sceneATS;
    @XmlElement(name = "LaneBCTS", required = true)
    protected BigInteger laneBCTS;
    @XmlElement(name = "RetNTS", required = true)
    protected BigInteger retNTS;
    @XmlElement(name = "ExcludeFromRep", required = true)
    protected BigInteger excludeFromRep;
    @XmlElement(name = "SecondaryIncident", required = true)
    protected BigInteger secondaryIncident;
    @XmlElement(name = "SecondaryIncidentLogNum")
    protected BigInteger secondaryIncidentLogNum;
    @XmlElement(name = "IncSeverity", required = true)
    protected BigInteger incSeverity;
    @XmlElement(name = "IncSeverityMod", required = true)
    protected BigInteger incSeverityMod;
    @XmlElement(name = "IncSeverityMaj", required = true)
    protected BigInteger incSeverityMaj;
    @XmlElement(name = "CREventID")
    protected String crEventID;
    @XmlElement(name = "DetectMethod", required = true)
    protected String detectMethod;
    @XmlElement(name = "LogType")
    protected BigInteger logType;

    /**
     * Gets the value of the closed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClosed() {
        return closed;
    }

    /**
     * Sets the value of the closed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setClosed(BigInteger value) {
        this.closed = value;
    }

    /**
     * Gets the value of the closedTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosedTime() {
        return closedTime;
    }

    /**
     * Sets the value of the closedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosedTime(String value) {
        this.closedTime = value;
    }

    /**
     * Gets the value of the lockedID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLockedID() {
        return lockedID;
    }

    /**
     * Sets the value of the lockedID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLockedID(BigInteger value) {
        this.lockedID = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the idx0020Key property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIDX0020Key() {
        return idx0020Key;
    }

    /**
     * Sets the value of the idx0020Key property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIDX0020Key(BigInteger value) {
        this.idx0020Key = value;
    }

    /**
     * Gets the value of the operatorsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorsResponse() {
        return operatorsResponse;
    }

    /**
     * Sets the value of the operatorsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorsResponse(String value) {
        this.operatorsResponse = value;
    }

    /**
     * Gets the value of the crossX0020Street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrossX0020Street() {
        return crossX0020Street;
    }

    /**
     * Sets the value of the crossX0020Street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrossX0020Street(String value) {
        this.crossX0020Street = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the routeX002FX0020Street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteX002FX0020Street() {
        return routeX002FX0020Street;
    }

    /**
     * Sets the value of the routeX002FX0020Street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteX002FX0020Street(String value) {
        this.routeX002FX0020Street = value;
    }

    /**
     * Gets the value of the municipality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipality() {
        return municipality;
    }

    /**
     * Sets the value of the municipality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipality(String value) {
        this.municipality = value;
    }

    /**
     * Gets the value of the eventX0020Description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventX0020Description() {
        return eventX0020Description;
    }

    /**
     * Sets the value of the eventX0020Description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventX0020Description(String value) {
        this.eventX0020Description = value;
    }

    /**
     * Gets the value of the callerX0020Organization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerX0020Organization() {
        return callerX0020Organization;
    }

    /**
     * Sets the value of the callerX0020Organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerX0020Organization(String value) {
        this.callerX0020Organization = value;
    }

    /**
     * Gets the value of the callerX0020PhoneX0020X0023 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerX0020PhoneX0020X0023() {
        return callerX0020PhoneX0020X0023;
    }

    /**
     * Sets the value of the callerX0020PhoneX0020X0023 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerX0020PhoneX0020X0023(String value) {
        this.callerX0020PhoneX0020X0023 = value;
    }

    /**
     * Gets the value of the callerX0020Name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerX0020Name() {
        return callerX0020Name;
    }

    /**
     * Sets the value of the callerX0020Name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerX0020Name(String value) {
        this.callerX0020Name = value;
    }

    /**
     * Gets the value of the genX0020Event property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenX0020Event() {
        return genX0020Event;
    }

    /**
     * Sets the value of the genX0020Event property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenX0020Event(String value) {
        this.genX0020Event = value;
    }

    /**
     * Gets the value of the operators property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperators() {
        return operators;
    }

    /**
     * Sets the value of the operators property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperators(String value) {
        this.operators = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the owningX0020Agency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwningX0020Agency() {
        return owningX0020Agency;
    }

    /**
     * Sets the value of the owningX0020Agency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwningX0020Agency(String value) {
        this.owningX0020Agency = value;
    }

    /**
     * Gets the value of the detectionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetectionTime() {
        return detectionTime;
    }

    /**
     * Sets the value of the detectionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetectionTime(String value) {
        this.detectionTime = value;
    }

    /**
     * Gets the value of the verifyTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerifyTime() {
        return verifyTime;
    }

    /**
     * Sets the value of the verifyTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerifyTime(String value) {
        this.verifyTime = value;
    }

    /**
     * Gets the value of the sceneArrTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSceneArrTime() {
        return sceneArrTime;
    }

    /**
     * Sets the value of the sceneArrTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSceneArrTime(String value) {
        this.sceneArrTime = value;
    }

    /**
     * Gets the value of the sceneArrTimeSpan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSceneArrTimeSpan() {
        return sceneArrTimeSpan;
    }

    /**
     * Sets the value of the sceneArrTimeSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSceneArrTimeSpan(BigInteger value) {
        this.sceneArrTimeSpan = value;
    }

    /**
     * Gets the value of the sceneArrTimeSpanMod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSceneArrTimeSpanMod() {
        return sceneArrTimeSpanMod;
    }

    /**
     * Sets the value of the sceneArrTimeSpanMod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSceneArrTimeSpanMod(BigInteger value) {
        this.sceneArrTimeSpanMod = value;
    }

    /**
     * Gets the value of the sceneArrTimeSpanMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSceneArrTimeSpanMax() {
        return sceneArrTimeSpanMax;
    }

    /**
     * Sets the value of the sceneArrTimeSpanMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSceneArrTimeSpanMax(BigInteger value) {
        this.sceneArrTimeSpanMax = value;
    }

    /**
     * Gets the value of the lanBlockClearTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanBlockClearTime() {
        return lanBlockClearTime;
    }

    /**
     * Sets the value of the lanBlockClearTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanBlockClearTime(String value) {
        this.lanBlockClearTime = value;
    }

    /**
     * Gets the value of the lanBlcokClearTimeSpan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLanBlcokClearTimeSpan() {
        return lanBlcokClearTimeSpan;
    }

    /**
     * Sets the value of the lanBlcokClearTimeSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLanBlcokClearTimeSpan(BigInteger value) {
        this.lanBlcokClearTimeSpan = value;
    }

    /**
     * Gets the value of the lanBlcokClearTimeSpanMod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLanBlcokClearTimeSpanMod() {
        return lanBlcokClearTimeSpanMod;
    }

    /**
     * Sets the value of the lanBlcokClearTimeSpanMod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLanBlcokClearTimeSpanMod(BigInteger value) {
        this.lanBlcokClearTimeSpanMod = value;
    }

    /**
     * Gets the value of the lanBlcokClearTimeSpanMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLanBlcokClearTimeSpanMax() {
        return lanBlcokClearTimeSpanMax;
    }

    /**
     * Sets the value of the lanBlcokClearTimeSpanMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLanBlcokClearTimeSpanMax(BigInteger value) {
        this.lanBlcokClearTimeSpanMax = value;
    }

    /**
     * Gets the value of the clearTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClearTime() {
        return clearTime;
    }

    /**
     * Sets the value of the clearTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClearTime(String value) {
        this.clearTime = value;
    }

    /**
     * Gets the value of the sceneDepartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSceneDepartTime() {
        return sceneDepartTime;
    }

    /**
     * Sets the value of the sceneDepartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSceneDepartTime(String value) {
        this.sceneDepartTime = value;
    }

    /**
     * Gets the value of the retNormTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetNormTime() {
        return retNormTime;
    }

    /**
     * Sets the value of the retNormTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetNormTime(String value) {
        this.retNormTime = value;
    }

    /**
     * Gets the value of the retNormTimeSpan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRetNormTimeSpan() {
        return retNormTimeSpan;
    }

    /**
     * Sets the value of the retNormTimeSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRetNormTimeSpan(BigInteger value) {
        this.retNormTimeSpan = value;
    }

    /**
     * Gets the value of the retNormTimeSpanMod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRetNormTimeSpanMod() {
        return retNormTimeSpanMod;
    }

    /**
     * Sets the value of the retNormTimeSpanMod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRetNormTimeSpanMod(BigInteger value) {
        this.retNormTimeSpanMod = value;
    }

    /**
     * Gets the value of the retNormTimeSpanMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRetNormTimeSpanMax() {
        return retNormTimeSpanMax;
    }

    /**
     * Sets the value of the retNormTimeSpanMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRetNormTimeSpanMax(BigInteger value) {
        this.retNormTimeSpanMax = value;
    }

    /**
     * Gets the value of the totalClearTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalClearTime() {
        return totalClearTime;
    }

    /**
     * Sets the value of the totalClearTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalClearTime(BigInteger value) {
        this.totalClearTime = value;
    }

    /**
     * Gets the value of the dms property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDMS() {
        return dms;
    }

    /**
     * Sets the value of the dms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDMS(BigInteger value) {
        this.dms = value;
    }

    /**
     * Gets the value of the dmsx0020ActX0020Time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDMSX0020ActX0020Time() {
        return dmsx0020ActX0020Time;
    }

    /**
     * Sets the value of the dmsx0020ActX0020Time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDMSX0020ActX0020Time(String value) {
        this.dmsx0020ActX0020Time = value;
    }

    /**
     * Gets the value of the dmsx0020DeActX0020Time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDMSX0020DeActX0020Time() {
        return dmsx0020DeActX0020Time;
    }

    /**
     * Sets the value of the dmsx0020DeActX0020Time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDMSX0020DeActX0020Time(String value) {
        this.dmsx0020DeActX0020Time = value;
    }

    /**
     * Gets the value of the pvms property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPVMS() {
        return pvms;
    }

    /**
     * Sets the value of the pvms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPVMS(BigInteger value) {
        this.pvms = value;
    }

    /**
     * Gets the value of the pvmsx0020ActX0020Time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPVMSX0020ActX0020Time() {
        return pvmsx0020ActX0020Time;
    }

    /**
     * Sets the value of the pvmsx0020ActX0020Time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPVMSX0020ActX0020Time(String value) {
        this.pvmsx0020ActX0020Time = value;
    }

    /**
     * Gets the value of the pvmsx0020DeActX0020Time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPVMSX0020DeActX0020Time() {
        return pvmsx0020DeActX0020Time;
    }

    /**
     * Sets the value of the pvmsx0020DeActX0020Time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPVMSX0020DeActX0020Time(String value) {
        this.pvmsx0020DeActX0020Time = value;
    }

    /**
     * Gets the value of the har property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHAR() {
        return har;
    }

    /**
     * Sets the value of the har property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHAR(BigInteger value) {
        this.har = value;
    }

    /**
     * Gets the value of the carsx0020Active property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCARSX0020Active() {
        return carsx0020Active;
    }

    /**
     * Sets the value of the carsx0020Active property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCARSX0020Active(BigInteger value) {
        this.carsx0020Active = value;
    }

    /**
     * Gets the value of the carsx0020Deactive property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCARSX0020Deactive() {
        return carsx0020Deactive;
    }

    /**
     * Sets the value of the carsx0020Deactive property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCARSX0020Deactive(BigInteger value) {
        this.carsx0020Deactive = value;
    }

    /**
     * Gets the value of the carsx0020ManX0020Act property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCARSX0020ManX0020Act() {
        return carsx0020ManX0020Act;
    }

    /**
     * Sets the value of the carsx0020ManX0020Act property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCARSX0020ManX0020Act(BigInteger value) {
        this.carsx0020ManX0020Act = value;
    }

    /**
     * Gets the value of the carsx0020ManX0020DeAct property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCARSX0020ManX0020DeAct() {
        return carsx0020ManX0020DeAct;
    }

    /**
     * Sets the value of the carsx0020ManX0020DeAct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCARSX0020ManX0020DeAct(BigInteger value) {
        this.carsx0020ManX0020DeAct = value;
    }

    /**
     * Gets the value of the websiteX0020AddedX0020Incident property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWebsiteX0020AddedX0020Incident() {
        return websiteX0020AddedX0020Incident;
    }

    /**
     * Sets the value of the websiteX0020AddedX0020Incident property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWebsiteX0020AddedX0020Incident(BigInteger value) {
        this.websiteX0020AddedX0020Incident = value;
    }

    /**
     * Gets the value of the websiteX0020DeletedX0020Incident property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWebsiteX0020DeletedX0020Incident() {
        return websiteX0020DeletedX0020Incident;
    }

    /**
     * Sets the value of the websiteX0020DeletedX0020Incident property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWebsiteX0020DeletedX0020Incident(BigInteger value) {
        this.websiteX0020DeletedX0020Incident = value;
    }

    /**
     * Gets the value of the laneBlocked property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLaneBlocked() {
        return laneBlocked;
    }

    /**
     * Sets the value of the laneBlocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLaneBlocked(BigInteger value) {
        this.laneBlocked = value;
    }

    /**
     * Gets the value of the modTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModTime() {
        return modTime;
    }

    /**
     * Sets the value of the modTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModTime(String value) {
        this.modTime = value;
    }

    /**
     * Gets the value of the fullRoadClosure property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFullRoadClosure() {
        return fullRoadClosure;
    }

    /**
     * Sets the value of the fullRoadClosure property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFullRoadClosure(BigInteger value) {
        this.fullRoadClosure = value;
    }

    /**
     * Gets the value of the dmsActiveList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDMSActiveList() {
        return dmsActiveList;
    }

    /**
     * Sets the value of the dmsActiveList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDMSActiveList(String value) {
        this.dmsActiveList = value;
    }

    /**
     * Gets the value of the transAlertX0020Act property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTransAlertX0020Act() {
        return transAlertX0020Act;
    }

    /**
     * Sets the value of the transAlertX0020Act property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTransAlertX0020Act(BigInteger value) {
        this.transAlertX0020Act = value;
    }

    /**
     * Gets the value of the transAlertX0020DeAct property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTransAlertX0020DeAct() {
        return transAlertX0020DeAct;
    }

    /**
     * Sets the value of the transAlertX0020DeAct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTransAlertX0020DeAct(BigInteger value) {
        this.transAlertX0020DeAct = value;
    }

    /**
     * Gets the value of the tcws property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTCWS() {
        return tcws;
    }

    /**
     * Sets the value of the tcws property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTCWS(BigInteger value) {
        this.tcws = value;
    }

    /**
     * Gets the value of the skyway property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSkyway() {
        return skyway;
    }

    /**
     * Sets the value of the skyway property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSkyway(BigInteger value) {
        this.skyway = value;
    }

    /**
     * Gets the value of the charmsEventNoAction property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCharmsEventNoAction() {
        return charmsEventNoAction;
    }

    /**
     * Sets the value of the charmsEventNoAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCharmsEventNoAction(BigInteger value) {
        this.charmsEventNoAction = value;
    }

    /**
     * Gets the value of the hicfSent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHICFSent() {
        return hicfSent;
    }

    /**
     * Sets the value of the hicfSent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHICFSent(BigInteger value) {
        this.hicfSent = value;
    }

    /**
     * Gets the value of the harSlot property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHARSlot() {
        return harSlot;
    }

    /**
     * Sets the value of the harSlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHARSlot(BigInteger value) {
        this.harSlot = value;
    }

    /**
     * Gets the value of the crdmsx0020Act property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCRDMSX0020Act() {
        return crdmsx0020Act;
    }

    /**
     * Sets the value of the crdmsx0020Act property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCRDMSX0020Act(BigInteger value) {
        this.crdmsx0020Act = value;
    }

    /**
     * Gets the value of the crdmsx0020DeAct property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCRDMSX0020DeAct() {
        return crdmsx0020DeAct;
    }

    /**
     * Sets the value of the crdmsx0020DeAct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCRDMSX0020DeAct(BigInteger value) {
        this.crdmsx0020DeAct = value;
    }

    /**
     * Gets the value of the crFaxEmailX0020Act property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCRFaxEmailX0020Act() {
        return crFaxEmailX0020Act;
    }

    /**
     * Sets the value of the crFaxEmailX0020Act property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCRFaxEmailX0020Act(BigInteger value) {
        this.crFaxEmailX0020Act = value;
    }

    /**
     * Gets the value of the crFaxEmailX0020DeAct property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCRFaxEmailX0020DeAct() {
        return crFaxEmailX0020DeAct;
    }

    /**
     * Sets the value of the crFaxEmailX0020DeAct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCRFaxEmailX0020DeAct(BigInteger value) {
        this.crFaxEmailX0020DeAct = value;
    }

    /**
     * Gets the value of the crWebX0020Act property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCRWebX0020Act() {
        return crWebX0020Act;
    }

    /**
     * Sets the value of the crWebX0020Act property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCRWebX0020Act(BigInteger value) {
        this.crWebX0020Act = value;
    }

    /**
     * Gets the value of the crWebX0020DeAct property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCRWebX0020DeAct() {
        return crWebX0020DeAct;
    }

    /**
     * Sets the value of the crWebX0020DeAct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCRWebX0020DeAct(BigInteger value) {
        this.crWebX0020DeAct = value;
    }

    /**
     * Gets the value of the numX0020LanesX0020Blocked property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumX0020LanesX0020Blocked() {
        return numX0020LanesX0020Blocked;
    }

    /**
     * Sets the value of the numX0020LanesX0020Blocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumX0020LanesX0020Blocked(BigInteger value) {
        this.numX0020LanesX0020Blocked = value;
    }

    /**
     * Gets the value of the hicfFinalSent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHICFFinalSent() {
        return hicfFinalSent;
    }

    /**
     * Sets the value of the hicfFinalSent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHICFFinalSent(BigInteger value) {
        this.hicfFinalSent = value;
    }

    /**
     * Gets the value of the sceneATS property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSceneATS() {
        return sceneATS;
    }

    /**
     * Sets the value of the sceneATS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSceneATS(BigInteger value) {
        this.sceneATS = value;
    }

    /**
     * Gets the value of the laneBCTS property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLaneBCTS() {
        return laneBCTS;
    }

    /**
     * Sets the value of the laneBCTS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLaneBCTS(BigInteger value) {
        this.laneBCTS = value;
    }

    /**
     * Gets the value of the retNTS property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRetNTS() {
        return retNTS;
    }

    /**
     * Sets the value of the retNTS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRetNTS(BigInteger value) {
        this.retNTS = value;
    }

    /**
     * Gets the value of the excludeFromRep property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExcludeFromRep() {
        return excludeFromRep;
    }

    /**
     * Sets the value of the excludeFromRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExcludeFromRep(BigInteger value) {
        this.excludeFromRep = value;
    }

    /**
     * Gets the value of the secondaryIncident property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSecondaryIncident() {
        return secondaryIncident;
    }

    /**
     * Sets the value of the secondaryIncident property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSecondaryIncident(BigInteger value) {
        this.secondaryIncident = value;
    }

    /**
     * Gets the value of the secondaryIncidentLogNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSecondaryIncidentLogNum() {
        return secondaryIncidentLogNum;
    }

    /**
     * Sets the value of the secondaryIncidentLogNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSecondaryIncidentLogNum(BigInteger value) {
        this.secondaryIncidentLogNum = value;
    }

    /**
     * Gets the value of the incSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIncSeverity() {
        return incSeverity;
    }

    /**
     * Sets the value of the incSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIncSeverity(BigInteger value) {
        this.incSeverity = value;
    }

    /**
     * Gets the value of the incSeverityMod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIncSeverityMod() {
        return incSeverityMod;
    }

    /**
     * Sets the value of the incSeverityMod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIncSeverityMod(BigInteger value) {
        this.incSeverityMod = value;
    }

    /**
     * Gets the value of the incSeverityMaj property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIncSeverityMaj() {
        return incSeverityMaj;
    }

    /**
     * Sets the value of the incSeverityMaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIncSeverityMaj(BigInteger value) {
        this.incSeverityMaj = value;
    }

    /**
     * Gets the value of the crEventID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREventID() {
        return crEventID;
    }

    /**
     * Sets the value of the crEventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREventID(String value) {
        this.crEventID = value;
    }

    /**
     * Gets the value of the detectMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetectMethod() {
        return detectMethod;
    }

    /**
     * Sets the value of the detectMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetectMethod(String value) {
        this.detectMethod = value;
    }

    /**
     * Gets the value of the logType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLogType() {
        return logType;
    }

    /**
     * Sets the value of the logType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLogType(BigInteger value) {
        this.logType = value;
    }

}
