//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 03:26:38 AM EST 
//


package edu.buffalo.csse.its.xmlbinding.trafficeventhistory;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ACTION" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="AREAS" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="ATEID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BLOCKEDLANE" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="CAUSE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CONFIRMATIONSOURCE" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="CONFIRMATIONTIME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="DETECTIONTIME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="DISTANCECOVERED" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="DISTRICT" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="ESTIMATEDDURATION" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="FULLCLOSURE" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="HEADLOCSTRING" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HEADLONGROADNAME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HEADVDSID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="INCIDENTID" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="INITIALNOTIFICATIONTIME" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="INJURIES" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="LEFTSHOULDER" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="LOCALUPDATETIME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="LONGDESC" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="NORMALTRAFFICFLOWTIME" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="NOTIFICATIONTIME" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="OCCURENCETIME" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="OWNER" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="QUEUEID" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="RIGHTSHOULDER" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="SECONDARY" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="SEVERITY" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="SOURCE" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="STATE" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="SUBCAUSE" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="TAILLOCSTRING" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TAILLONGROADNAME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TAILVDSID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TETYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="TOWN" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="TRANSITTYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="UNIVERSALUPDATETIME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="VEHICLESINVOLVED" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="VERIFICATIONTIME" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="WRECKERCLEARSLANES" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ROW")
public class ROW {

    @XmlAttribute(name = "ACTION", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String action;
    @XmlAttribute(name = "AREAS", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String areas;
    @XmlAttribute(name = "ATEID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ateid;
    @XmlAttribute(name = "BLOCKEDLANE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String blockedlane;
    @XmlAttribute(name = "CAUSE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String cause;
    @XmlAttribute(name = "CONFIRMATIONSOURCE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String confirmationsource;
    @XmlAttribute(name = "CONFIRMATIONTIME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String confirmationtime;
    @XmlAttribute(name = "DETECTIONTIME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String detectiontime;
    @XmlAttribute(name = "DISTANCECOVERED", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String distancecovered;
    @XmlAttribute(name = "DISTRICT", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String district;
    @XmlAttribute(name = "ESTIMATEDDURATION", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String estimatedduration;
    @XmlAttribute(name = "FULLCLOSURE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fullclosure;
    @XmlAttribute(name = "HEADLOCSTRING", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String headlocstring;
    @XmlAttribute(name = "HEADLONGROADNAME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String headlongroadname;
    @XmlAttribute(name = "HEADVDSID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String headvdsid;
    @XmlAttribute(name = "INCIDENTID", required = true)
    protected BigDecimal incidentid;
    @XmlAttribute(name = "INITIALNOTIFICATIONTIME", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String initialnotificationtime;
    @XmlAttribute(name = "INJURIES", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String injuries;
    @XmlAttribute(name = "LEFTSHOULDER", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String leftshoulder;
    @XmlAttribute(name = "LOCALUPDATETIME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String localupdatetime;
    @XmlAttribute(name = "LONGDESC", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String longdesc;
    @XmlAttribute(name = "NORMALTRAFFICFLOWTIME", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String normaltrafficflowtime;
    @XmlAttribute(name = "NOTIFICATIONTIME", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String notificationtime;
    @XmlAttribute(name = "OCCURENCETIME", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String occurencetime;
    @XmlAttribute(name = "OWNER", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String owner;
    @XmlAttribute(name = "QUEUEID", required = true)
    protected BigDecimal queueid;
    @XmlAttribute(name = "RIGHTSHOULDER", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String rightshoulder;
    @XmlAttribute(name = "SECONDARY", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String secondary;
    @XmlAttribute(name = "SEVERITY", required = true)
    protected BigDecimal severity;
    @XmlAttribute(name = "SOURCE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String source;
    @XmlAttribute(name = "STATE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String state;
    @XmlAttribute(name = "SUBCAUSE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String subcause;
    @XmlAttribute(name = "TAILLOCSTRING", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String taillocstring;
    @XmlAttribute(name = "TAILLONGROADNAME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String taillongroadname;
    @XmlAttribute(name = "TAILVDSID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String tailvdsid;
    @XmlAttribute(name = "TETYPE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tetype;
    @XmlAttribute(name = "TOWN", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String town;
    @XmlAttribute(name = "TRANSITTYPE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String transittype;
    @XmlAttribute(name = "UNIVERSALUPDATETIME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String universalupdatetime;
    @XmlAttribute(name = "VEHICLESINVOLVED", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String vehiclesinvolved;
    @XmlAttribute(name = "VERIFICATIONTIME", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String verificationtime;
    @XmlAttribute(name = "WRECKERCLEARSLANES", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String wreckerclearslanes;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTION() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTION(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the areas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAREAS() {
        return areas;
    }

    /**
     * Sets the value of the areas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAREAS(String value) {
        this.areas = value;
    }

    /**
     * Gets the value of the ateid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getATEID() {
        return ateid;
    }

    /**
     * Sets the value of the ateid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setATEID(String value) {
        this.ateid = value;
    }

    /**
     * Gets the value of the blockedlane property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBLOCKEDLANE() {
        return blockedlane;
    }

    /**
     * Sets the value of the blockedlane property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBLOCKEDLANE(String value) {
        this.blockedlane = value;
    }

    /**
     * Gets the value of the cause property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAUSE() {
        return cause;
    }

    /**
     * Sets the value of the cause property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAUSE(String value) {
        this.cause = value;
    }

    /**
     * Gets the value of the confirmationsource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFIRMATIONSOURCE() {
        return confirmationsource;
    }

    /**
     * Sets the value of the confirmationsource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFIRMATIONSOURCE(String value) {
        this.confirmationsource = value;
    }

    /**
     * Gets the value of the confirmationtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFIRMATIONTIME() {
        return confirmationtime;
    }

    /**
     * Sets the value of the confirmationtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFIRMATIONTIME(String value) {
        this.confirmationtime = value;
    }

    /**
     * Gets the value of the detectiontime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDETECTIONTIME() {
        return detectiontime;
    }

    /**
     * Sets the value of the detectiontime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDETECTIONTIME(String value) {
        this.detectiontime = value;
    }

    /**
     * Gets the value of the distancecovered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDISTANCECOVERED() {
        return distancecovered;
    }

    /**
     * Sets the value of the distancecovered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDISTANCECOVERED(String value) {
        this.distancecovered = value;
    }

    /**
     * Gets the value of the district property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDISTRICT() {
        return district;
    }

    /**
     * Sets the value of the district property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDISTRICT(String value) {
        this.district = value;
    }

    /**
     * Gets the value of the estimatedduration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getESTIMATEDDURATION() {
        return estimatedduration;
    }

    /**
     * Sets the value of the estimatedduration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setESTIMATEDDURATION(String value) {
        this.estimatedduration = value;
    }

    /**
     * Gets the value of the fullclosure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFULLCLOSURE() {
        return fullclosure;
    }

    /**
     * Sets the value of the fullclosure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFULLCLOSURE(String value) {
        this.fullclosure = value;
    }

    /**
     * Gets the value of the headlocstring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHEADLOCSTRING() {
        return headlocstring;
    }

    /**
     * Sets the value of the headlocstring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHEADLOCSTRING(String value) {
        this.headlocstring = value;
    }

    /**
     * Gets the value of the headlongroadname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHEADLONGROADNAME() {
        return headlongroadname;
    }

    /**
     * Sets the value of the headlongroadname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHEADLONGROADNAME(String value) {
        this.headlongroadname = value;
    }

    /**
     * Gets the value of the headvdsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHEADVDSID() {
        return headvdsid;
    }

    /**
     * Sets the value of the headvdsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHEADVDSID(String value) {
        this.headvdsid = value;
    }

    /**
     * Gets the value of the incidentid property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getINCIDENTID() {
        return incidentid;
    }

    /**
     * Sets the value of the incidentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setINCIDENTID(BigDecimal value) {
        this.incidentid = value;
    }

    /**
     * Gets the value of the initialnotificationtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINITIALNOTIFICATIONTIME() {
        return initialnotificationtime;
    }

    /**
     * Sets the value of the initialnotificationtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINITIALNOTIFICATIONTIME(String value) {
        this.initialnotificationtime = value;
    }

    /**
     * Gets the value of the injuries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINJURIES() {
        return injuries;
    }

    /**
     * Sets the value of the injuries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINJURIES(String value) {
        this.injuries = value;
    }

    /**
     * Gets the value of the leftshoulder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEFTSHOULDER() {
        return leftshoulder;
    }

    /**
     * Sets the value of the leftshoulder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEFTSHOULDER(String value) {
        this.leftshoulder = value;
    }

    /**
     * Gets the value of the localupdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCALUPDATETIME() {
        return localupdatetime;
    }

    /**
     * Sets the value of the localupdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCALUPDATETIME(String value) {
        this.localupdatetime = value;
    }

    /**
     * Gets the value of the longdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLONGDESC() {
        return longdesc;
    }

    /**
     * Sets the value of the longdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLONGDESC(String value) {
        this.longdesc = value;
    }

    /**
     * Gets the value of the normaltrafficflowtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNORMALTRAFFICFLOWTIME() {
        return normaltrafficflowtime;
    }

    /**
     * Sets the value of the normaltrafficflowtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNORMALTRAFFICFLOWTIME(String value) {
        this.normaltrafficflowtime = value;
    }

    /**
     * Gets the value of the notificationtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOTIFICATIONTIME() {
        return notificationtime;
    }

    /**
     * Sets the value of the notificationtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOTIFICATIONTIME(String value) {
        this.notificationtime = value;
    }

    /**
     * Gets the value of the occurencetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOCCURENCETIME() {
        return occurencetime;
    }

    /**
     * Sets the value of the occurencetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOCCURENCETIME(String value) {
        this.occurencetime = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOWNER() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOWNER(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the queueid property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQUEUEID() {
        return queueid;
    }

    /**
     * Sets the value of the queueid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQUEUEID(BigDecimal value) {
        this.queueid = value;
    }

    /**
     * Gets the value of the rightshoulder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRIGHTSHOULDER() {
        return rightshoulder;
    }

    /**
     * Sets the value of the rightshoulder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRIGHTSHOULDER(String value) {
        this.rightshoulder = value;
    }

    /**
     * Gets the value of the secondary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECONDARY() {
        return secondary;
    }

    /**
     * Sets the value of the secondary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECONDARY(String value) {
        this.secondary = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSEVERITY() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSEVERITY(BigDecimal value) {
        this.severity = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOURCE() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOURCE(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATE() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATE(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the subcause property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBCAUSE() {
        return subcause;
    }

    /**
     * Sets the value of the subcause property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBCAUSE(String value) {
        this.subcause = value;
    }

    /**
     * Gets the value of the taillocstring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAILLOCSTRING() {
        return taillocstring;
    }

    /**
     * Sets the value of the taillocstring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAILLOCSTRING(String value) {
        this.taillocstring = value;
    }

    /**
     * Gets the value of the taillongroadname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAILLONGROADNAME() {
        return taillongroadname;
    }

    /**
     * Sets the value of the taillongroadname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAILLONGROADNAME(String value) {
        this.taillongroadname = value;
    }

    /**
     * Gets the value of the tailvdsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAILVDSID() {
        return tailvdsid;
    }

    /**
     * Sets the value of the tailvdsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAILVDSID(String value) {
        this.tailvdsid = value;
    }

    /**
     * Gets the value of the tetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTETYPE() {
        return tetype;
    }

    /**
     * Sets the value of the tetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTETYPE(String value) {
        this.tetype = value;
    }

    /**
     * Gets the value of the town property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOWN() {
        return town;
    }

    /**
     * Sets the value of the town property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOWN(String value) {
        this.town = value;
    }

    /**
     * Gets the value of the transittype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANSITTYPE() {
        return transittype;
    }

    /**
     * Sets the value of the transittype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSITTYPE(String value) {
        this.transittype = value;
    }

    /**
     * Gets the value of the universalupdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNIVERSALUPDATETIME() {
        return universalupdatetime;
    }

    /**
     * Sets the value of the universalupdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNIVERSALUPDATETIME(String value) {
        this.universalupdatetime = value;
    }

    /**
     * Gets the value of the vehiclesinvolved property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVEHICLESINVOLVED() {
        return vehiclesinvolved;
    }

    /**
     * Sets the value of the vehiclesinvolved property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVEHICLESINVOLVED(String value) {
        this.vehiclesinvolved = value;
    }

    /**
     * Gets the value of the verificationtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVERIFICATIONTIME() {
        return verificationtime;
    }

    /**
     * Sets the value of the verificationtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVERIFICATIONTIME(String value) {
        this.verificationtime = value;
    }

    /**
     * Gets the value of the wreckerclearslanes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWRECKERCLEARSLANES() {
        return wreckerclearslanes;
    }

    /**
     * Sets the value of the wreckerclearslanes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWRECKERCLEARSLANES(String value) {
        this.wreckerclearslanes = value;
    }

}
